# Generated by Django 4.2.1 on 2023-09-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_coin_options_alter_coin_telegram_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='launch_date',
        ),
    ]
