# Generated by Django 4.2.1 on 2023-09-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_coin_launch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='listing_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на листинг'),
        ),
    ]
