# Generated by Django 4.2.1 on 2023-10-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_setting_copyright_en_setting_copyright_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='promote_text',
            field=models.TextField(blank=True, verbose_name='Текст (Promote)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='promote_text_banner',
            field=models.TextField(blank=True, verbose_name='Текст (Promote Banner)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='promote_text_spot',
            field=models.TextField(blank=True, verbose_name='Текст (Promote Spot)'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='binance_smart_chain',
            field=models.CharField(blank=True, null=True, verbose_name='Контрактный адрес'),
        ),
    ]
