# Generated by Django 4.2.1 on 2023-10-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_setting_promote_text_setting_promote_text_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='promote_text_banner_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст (Promote Banner)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='promote_text_banner_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст (Promote Banner)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='promote_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст (Promote)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='promote_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст (Promote)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='promote_text_spot_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст (Promote Spot)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='promote_text_spot_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст (Promote Spot)'),
        ),
    ]
