# Generated by Django 4.2.1 on 2023-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_setting_promote_text_banner_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='promote_stat_1',
            field=models.IntegerField(default=0, verbose_name='(Promote Статистика) Пользователи'),
        ),
        migrations.AddField(
            model_name='setting',
            name='promote_stat_2',
            field=models.IntegerField(default=0, verbose_name='(Promote Статистика) Twitter'),
        ),
        migrations.AddField(
            model_name='setting',
            name='promote_stat_3',
            field=models.IntegerField(default=0, verbose_name='(Promote Статистика) Newsletter'),
        ),
    ]
