# Generated by Django 4.2.1 on 2023-10-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_setting_promote_stat_1_setting_promote_stat_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
