# Generated by Django 4.2.1 on 2024-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_listing_title_en_listing_title_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('question', models.TextField(verbose_name='Вопрос пользователя')),
            ],
        ),
    ]
