# Generated by Django 4.2.1 on 2024-04-06 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_alter_category_order_alter_networkchain_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='Дата начала продвижения')),
                ('finish_at', models.DateField(blank=True, null=True, verbose_name='Дата окончания продвижения')),
                ('type', models.CharField(choices=[('Banner', 'Banner'), ('Promoted', 'Promoted')], default='Banner', max_length=20, verbose_name='Тип продвижения')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coin', verbose_name='Монета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
