# Generated by Django 4.2.1 on 2024-04-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Изображение для url'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Изображение для url'),
        ),
    ]
