# Generated by Django 4.2.1 on 2024-04-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_coin_image_url_page_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='coins/', verbose_name='Изображение для url'),
        ),
    ]
