# Generated by Django 4.2.1 on 2024-04-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_coin_all_time_high_coin_all_time_high_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='api',
            field=models.CharField(blank=True, choices=[('uniswap', 'Uniswap'), ('coinranking', 'Coinranking')], default='coinranking', help_text='Выберите API для получения данных', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='all_time_high',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Максимум цени'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='all_time_high_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата максимума цени'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume_24h',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Объем торгов за 24 часа'),
        ),
    ]
