# Generated by Django 4.2.1 on 2024-04-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_coin_api_alter_coin_all_time_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='today_high',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Сегодняшний максимум'),
        ),
        migrations.AddField(
            model_name='coin',
            name='today_low',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Сегодняшний минимум'),
        ),
    ]
