# Generated by Django 4.2.1 on 2024-04-30 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_coin_today_high_coin_today_low'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название биржи')),
                ('logo', models.ImageField(upload_to='exchanges/logos/', verbose_name='Логотип биржи')),
            ],
        ),
        migrations.CreateModel(
            name='CoinExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='core.coin', verbose_name='Монета')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='core.exchange', verbose_name='Биржа')),
            ],
        ),
    ]
