# Generated by Django 4.2.1 on 2024-05-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_exchange_coinexchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='today_high',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='today_low',
        ),
    ]
