# Generated by Django 4.2.1 on 2024-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_coin_today_high_remove_coin_today_low'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
