# Generated by Django 4.2.1 on 2024-05-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_referencecurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencecurrency',
            name='name_en',
            field=models.CharField(blank=True, help_text='Полное наименование валюты (Bitcoin, US Dollar, Ethereum, ...)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referencecurrency',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Полное наименование валюты (Bitcoin, US Dollar, Ethereum, ...)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='referencecurrency',
            name='name',
            field=models.CharField(blank=True, help_text='Полное наименование валюты (Bitcoin, US Dollar, Ethereum, ...)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='referencecurrency',
            name='sign',
            field=models.CharField(blank=True, help_text='Символ валюты ($, €, £, ...)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='referencecurrency',
            name='symbol',
            field=models.CharField(help_text='Наименование валюты (BTC, USD, ETH, ...)', max_length=10),
        ),
    ]
