# Generated by Django 4.2.1 on 2024-05-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_referencecurrency_name_en_referencecurrency_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencecurrency',
            options={'ordering': ['symbol']},
        ),
        migrations.RemoveField(
            model_name='referencecurrency',
            name='sign',
        ),
        migrations.AddField(
            model_name='referencecurrency',
            name='price_to_usd',
            field=models.FloatField(default=0.0, help_text='Цена валюты к USD'),
        ),
    ]
