# Generated by Django 4.2.1 on 2024-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_referencecurrency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencecurrency',
            name='currency_type',
            field=models.CharField(choices=[('fiat', 'Fiat Currency'), ('crypto', 'Cryptocurrency')], default='fiat', max_length=10),
        ),
    ]
