# Generated by Django 4.2.1 on 2024-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_referencecurrency_currency_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='binance_smart_chain',
            new_name='contract_address',
        ),
        migrations.AddField(
            model_name='coin',
            name='network_name',
            field=models.CharField(blank=True, null=True, verbose_name='Название сети'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='listing_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на листинг'),
        ),
    ]
