# Generated by Django 4.2.1 on 2024-05-21 17:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_binance_smart_chain_coin_contract_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='coin_name', unique=True, verbose_name='Слаг'),
        ),
    ]
