# Generated by Django 4.2.1 on 2024-05-21 17:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_coin_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='coin_name', unique=True, verbose_name='Слаг'),
        ),
    ]
