# Generated by Django 4.2.1 on 2024-07-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_category_draft_listingplatform_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='description_seo_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание для seo'),
        ),
        migrations.AddField(
            model_name='coin',
            name='description_seo_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание для seo'),
        ),
        migrations.AddField(
            model_name='coin',
            name='title_seo_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название для seo'),
        ),
        migrations.AddField(
            model_name='coin',
            name='title_seo_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название для seo'),
        ),
    ]
