# Generated by Django 4.2.1 on 2024-10-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_listing_description_seo_listing_description_seo_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingitem',
            name='is_read_by_admin',
            field=models.BooleanField(default=False, verbose_name='Прочитано администратором'),
        ),
        migrations.AddField(
            model_name='coin',
            name='is_read_by_admin',
            field=models.BooleanField(default=False, verbose_name='Прочитано администратором'),
        ),
    ]
