# Generated by Django 4.2.1 on 2024-03-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_vote',
        ),
        migrations.AddField(
            model_name='user',
            name='first_vote',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата первого голоса'),
        ),
    ]
